ug_scholar/api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('', views.OverviewAPI.as_view(), name='overview'),
    path('populate-db/', views.PopulateDBAPIView.as_view(), name='populate-db'),
]

ug_scholar/dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"

# dashboard
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

# administrators
urlpatterns += [
    path('administrators/', views.AdministratorsView.as_view(), name='administrators'),
    path('create-administrator/', views.CreateUpdateAdministratorView.as_view(), name='create_administrator'), #noqa
]

# author and publications
urlpatterns += [
    path('authors/', views.AuthorsView.as_view(), name='authors'),
    path('create-author/', views.CreateUpdateAuthorView.as_view(), name='create_author'),
    path('publications/', views.PublicationsView.as_view(), name='publications'),
    path('download-sample-file/', views.DownloadSampleBulkFileView.as_view(), name='download_aut_csv'), #noqa
    path('bulk-upload-authors/', views.BulkUploadAuthorView.as_view(), name='bulk_upload_authors'), #noqa
]

# breakdown
urlpatterns += [
    path('colleges/', views.CollegesView.as_view(), name='colleges'),
    path('college-details/', views.CollegeDetailsView.as_view(), name='college_details'),
    path('institutions-and-centers/', views.FacultiesView.as_view(), name='faculties'),
    path('institution-details/', views.FacultyDetailsView.as_view(), name='institution_details'),
    path('departments/', views.DepartmentsView.as_view(), name='departments'),
    path('department-details/', views.DepartmentDetailsView.as_view(), name='department_details'), #noqa
]

# profile
urlpatterns += [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('change-profile-picture/', views.ChangeProfilePictureView.as_view(), name='change_pp'), #noqa
]

# logs
urlpatterns += [
    path('logs/', views.LogsView.as_view(), name='logs'),
]

ug_scholar/ug_scholar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('accounts.urls')),
    path('api/', include('api.urls')),
]


# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

ug_scholar/dashboard/models.py
from django.db import models

# Create your models here.

ug_scholar/dashboard/forms.py
from django import forms

from api.models import Profile


class AuthorProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['thumbnail', 'statistics', ]

ug_scholar/dashboard/views/administrators.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views import View

from accounts.models import User
from ug_scholar.library.decorators import AdministratorsOnly
from ug_scholar.library.utils_functions import log_user_action


class AdministratorsView(View):
    '''Renders the administrators page'''
    template_name = 'pages/administrators.html'
    
    @method_decorator(AdministratorsOnly)
    def get(self, request):
        user = request.user
        administrators = User.objects.all()
        log_user_action(user, "Viewed administrators page")
        context = {
            'administrators': administrators
        }
        return render(request, self.template_name, context)
    
  
class CreateUpdateAdministratorView(View):
    '''Renders the create/update administrators page'''
    
    @method_decorator(AdministratorsOnly)
    def get(self, request):
        user = request.user
        log_user_action(user, "Tried to access admin creation form via get request")
        return redirect('dashboard:administrators')    
    
    @method_decorator(AdministratorsOnly)
    def post(self, request):
        user = request.user
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        fullname = request.POST.get('fullname')
        
        admin = User.objects.filter(email=email).first()
        if password != password2:
            log_user_action(user, "Tried to create admin account with mismatching passwords")
            messages.info(request, "Passwords Do Not Match")
            return redirect('dashboard:administrators')
        
        if admin is not None:
            log_user_action(user, "Tried to create admin account with an already existing email")
            messages.info(request, "Email is Already Associated with an Account")
            return redirect('dashboard:administrators')
        try:
            new_admin = User.objects.create_user(email=email, password=password, fullname=fullname)
            new_admin.is_staff = True
            new_admin.save()
        except Exception as e:
            log_user_action(user, f"Tried to create admin account but error occured: {str(e)}")
            messages.info(request, "Error Creating Administrator Account")
            return redirect('dashboard:administrators')
        else:
            log_user_action(user, f"Created admin account: {new_admin.fullname} successfully")
            messages.success(request, "Administrator Account Created Successfully")
        return redirect('dashboard:administrators')

ug_scholar/dashboard/views/authors.py
import csv
import os
import json
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.utils.html import strip_tags
from django.views import View

from api.models import Author, Profile, Publication
from dashboard.forms import AuthorProfileForm
from dashboard.views import publications
from dashboard.views.publications import PublicationsView
from ug_scholar.library.constants import UG, SampleAuthorData
from ug_scholar.library.decorators import AdministratorsOnly
from ug_scholar.library.utils_functions import get_author_ids, log_user_action, scrape_author_data


class AuthorsView(View):
    '''Renders the authors profiles page - profiles page'''
    template_name = 'pages/authors.html'

    def get(self, request):
        ug = UG()
        authors = Profile.objects.all()

        schools = ug.get_schools()
        departments = ug.get_departments()
        colleges = ug.get_colleges()
        ranks = ug.get_ranks()

        context = {
            'authors': authors,
            'colleges': colleges,
            'schools': schools,
            'departments': departments,
            'ranks': ranks,
        }
        return render(request, self.template_name, context)


class CreateUpdateAuthorView(View):
    '''Renders the create/update author page'''

    def get(self, request):
        user = request.user
        log_user_action(user, "Tried to access author form using get request")
        return redirect('dashboard:authors')

    @method_decorator(AdministratorsOnly)
    def post(self, request):
        user = request.user
        scholar_id = request.POST.get('scholar_id')
        profile = Profile.objects.filter(scholar_id=scholar_id).first()
        if profile is not None:
            log_user_action(user, "Tried to create author profile with an already existing scholar id") #noqa
            messages.info(request, "Author Profile Already Exists")
            return redirect('dashboard:authors')
        # author does not exist, create new author profile
        print(f"Scrapping author data for profile: {scholar_id}")
        try:
            scraped = scrape_author_data(scholar_id)
        except Exception as e:
            messages.info(request, f"Error occured: {e}")
            return redirect('dashboard:authors')
        author_data = scraped["author_data"]
        form = AuthorProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            if author_data is not None or author_data != {}:
                profile.name = author_data['name']
                profile.affiliation = author_data['affiliations']
                profile.thumbnail = author_data['thumbnail']
                profile.interests = json.dumps(author_data['interests'])
                profile.statistics = json.dumps(author_data['cited_by_table'])
            profile.save()
            author = Author.objects.create(profile=profile)
            author.save()
            log_user_action(user, f"Created author profile: {profile.name} successfully") #noqa
            messages.success(request, "Author Profile Created Successfully")
            return redirect('dashboard:authors')
        else:
            for field, error in form.errors.items():
                message = f"{field.title()}: {strip_tags(error)}"
                log_user_action(user, f"Tried to create author profile but error occured: {message}") #noqa
                messages.info(request, message)
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class BulkUploadAuthorView(View):
    '''Used to implement bulk upload of author profiles: POST request'''

    def get(self, request):
        user = request.user
        log_user_action(user, "Tried to access bulk upload author form using get request")  # noqa
        return redirect('dashboard:authors')

    def post(self, request):
        updated_authors = 0
        updated_publications = 0
        csv_file = request.FILES.get('csv_file')
        try:
            infos = get_author_ids(csv_file)
        except Exception as e:
            messages.info(request, f"Error occured: {e}")
            return redirect('dashboard:authors')

        for info in infos:
            old_profile = Profile.objects.filter(scholar_id=info['author_id']).first()  # noqa
            if old_profile is not None:
                print(f"Skipping Profile: {old_profile.name}")
                print("+==================================================+")
                print("+==================================================+")
                continue
            scraped = scrape_author_data(info['author_id'])
            author_data = scraped["author_data"]
            # check if profile exists  - if not create profile
            profile = Profile.objects.filter(scholar_id=info['author_id']).first()  # noqa
            if profile is None:
                profile = Profile.objects.create(
                    name=author_data['name'],
                    scholar_id=info['author_id'],
                    affiliation=author_data['affiliations'],
                    thumbnail=author_data['thumbnail'],
                    interests=json.dumps(author_data['interests']),
                    statistics=json.dumps(author_data['cited_by_table']),
                    rank=info['rank'],
                    email=info['email'],
                    college=info['college'],
                    school=info['school'],
                    department=info['department'],
                )
                profile.save()
                print(f"Created profile: {profile.name}")
            
            # check if author exists. if not create author
            author = Author.objects.filter(profile=profile).first()
            if author is None:
                author = Author.objects.create(profile=profile)
                author.save()
            # get all authors articles/publications
            author_articles = scraped["author_articles"]

            print(f"Updating author: {author.profile.name}")
            # create publications
            for article in author_articles:
                publication = Publication.objects.filter(citation_id=article['article_citation_id']).first()  # noqa
                # Handle null citation values
                citation_value = article['article_cited_by_value']
                article_year = article['article_year']
                if citation_value is None or citation_value == "":
                    citation_value = 0
                else:
                    # make sure citation value is an integer
                    citation_value = int(citation_value)
                if article_year is None or article_year == "":
                    article_year = 1900
                else:
                    # make sure article year is a number
                    article_year = int(article_year)

                if publication is None:
                    # create new publication
                    publication = Publication.objects.create(
                        title=article['article_title'],
                        year=article_year,
                        link=article['article_link'],
                        citation_id=article['article_citation_id'],
                        authors=article['article_authors'],
                        journal=article['article_publication'],
                        citations=citation_value,
                    )
                    publication.save()
                else:
                    # update publication
                    publication.title = article['article_title']
                    publication.year = article_year
                    publication.link = article['article_link'],
                    publication.citation_id = article['article_citation_id']
                    publication.authors = article['article_authors']
                    publication.journal = article['article_publication']
                    publication.citations = citation_value
                    publication.save()
                # add publication to author if not already added
                if publication not in author.publications.all():
                    author.publications.add(publication)
                    author.save()
                else:
                    # remove the old publication and add the new one
                    author.publications.remove(publication)
                    author.publications.add(publication)
                    author.save()
                # update the count of updated publications and authors
                updated_publications += 1
            updated_authors += 1
        messages.success(request, f"Updated {updated_authors} authors with {updated_publications} publications")  # noqa
        log_user_action(request.user, "Updated the system using bulk author upload successfully")  # noqa
        return redirect('dashboard:authors')


class DownloadSampleBulkFileView(View):
    '''Used to download a sample csv file for bulk upload'''

    def get(self, request):
        sample_data = SampleAuthorData().get_author_sample_data()
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="bulk_author_upload_sample.csv"'

        writer = csv.writer(response)
        writer.writerow(['scholar', 'email', "college", 'school', 'department', 'rank']) # noqa
        
        for data in sample_data:
            writer.writerow([data['scholar'], data['email'], data['college'], data['school'], data['department'], data['rank']])
            
        return response

ug_scholar/dashboard/views/logs.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View

from accounts.models import UserLog
from ug_scholar.library.decorators import AdministratorsOnly
from ug_scholar.library.utils_functions import log_user_action


class LogsView(View):
    '''Renders the logs page'''
    template_name = 'pages/logs.html'
    
    @method_decorator(AdministratorsOnly)
    def get(self, request):
        user = request.user
        logs = UserLog.objects.all().order_by("-created_at")
        context = {
           "logs": logs
        }
        log_user_action(user, "Accessed the logs page")
        return render(request, self.template_name, context)
    
    

ug_scholar/dashboard/views/publications.py
from django.shortcuts import render
from django.views import View

from api.models import Publication


class PublicationsView(View):
    template_name = 'pages/publications.html'
    
    def get(self, request):
        publications = Publication.objects.all()
        
        context = {
            'publications': publications,
        }
        return render(request, self.template_name, context)

ug_scholar/dashboard/templates/pages/authors.html
{% extends "base/base.html" %}
{% load static %}
{% block content %}
<div class="page-wrapper">
    <div class="page-content">
        {% if messages %}
        {% for message in messages %}
        <div class="container">
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
        </div>
        {% endfor %}
        {% endif %}

        <!--breadcrumb-->
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            <div class="breadcrumb-title pe-3">Authors</div>
            <div class="ps-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}"><i class="bx bx-home-alt"></i></a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Authors</li>
                    </ol>
                </nav>
            </div>

            {% if request.user.is_superuser or request.user.staff %}
            <div class="ms-auto">
                <div class="btn-group">
                    <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#authorForm">Add Author</button>
                    <button type="button" class="btn btn-info" data-bs-toggle="modal" data-bs-target="#bulkAuthor">Bulk Author Upload</button>
                </div>
            </div>
            {% endif %}
        </div>
        <!--end breadcrumb-->
        <h6 class="mb-0 text-uppercase">Authors Information</h6>
        <hr/>
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>Profile</th>
                                <th>NAME</th>
                                <th>Rank</th>
                                <th>PUBS</th>
                                <th>CTS</th>
                                <th>H-INDEX</th>
                                <th>I10-IND</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if authors %}
                            {% for author in authors %}
                            <tr>
                                <td> <img src=" {% if author.thumbnail %} {{author.thumbnail}} {% else %} https://scholar.google.com/citations/images/avatar_scholar_128.png {% endif %} " style="height: 60px; width:auto;"></td> 
                                
                                <td>
                                    <a href="https://scholar.google.com/citations?hl=en&user={{author.scholar_id}}" target="_blank">
                                    {{author.name}} <br> <small style="color: lightblue;">{{author.college}}</small> 
                                </a>
                                </td> 
                                <td>{{author.rank}}</td> 
                                <td>{{author.get_author_publications}}</td>
                                <td>{{author.get_author_citations}}</td>
                                <td>{{author.get_author_hindex}}</td>
                                <td>{{author.get_author_i10index}}</td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="7">No Authors Found</td>
                            </tr>
                            {% endif %}

                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Profile</th>
                                <th>NAME</th>
                                <th>Rank</th>
                                <th>PUBS</th>
                                <th>CTS</th>
                                <th>H-INDEX</th>
                                <th>I10-INDEX</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Author form modal -->
<div class="modal fade" id="authorForm" tabindex="-1" aria-labelledby="authorFormLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable"" >
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="authorFormLabel">Create Single Author</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="{% url 'dashboard:create_author' %}" method="POST">
                {% csrf_token %}
                <div class="form-group mb-2">
                    <label for="name">Name</label>
                    <input type="text" name="name" placeholder="Author Name" class="form-control">
                </div>
                <div class="form-group mb-2">
                    <label for="email">Email</label>
                    <input type="email" name="email" placeholder="eg. princek@gmail.com" class="form-control">
                </div>
                <div class="form-group mb-2">
                    <label for="rank">Rank</label>
                    <!-- <input type="text" name="rank" placeholder="eg. Associate Professor" class="form-control"> -->
                    <select name="rank" class="form-control">
                        {% for rank in ranks %}
                        <option value="{{rank}}">{{rank}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group mb-2">
                    <label for="scholar_id">Scholar ID</label>
                    <input type="text" name="scholar_id" placeholder="Google Scholar ID" class="form-control">
                </div>
                <div class="form-group mb-2">
                    <label for="affiliation">Affiliation</label>
                    <input type="text" name="affiliation" placeholder="eg. University of Ghana" class="form-control">
                </div>
                <div class="form-group mb-2">
                    <label for="interests">Interests</label>
                    <input type="text" name="interests" placeholder="eg. Cloud Computing, Artificial Intelligence" class="form-control">
                </div>
                <div class="form-group mb-2">
                    <label for="college">College</label>
                    <select class="form-control" name="college" id="college">
                        {% for college in colleges %}
                        <option value="{{college}}">{{college}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group mb-2">
                    <label for="school">School / Institution</label>
                    <select class="form-control" name="school" id="school">
                        {% for school in schools %}
                        <option value="{{school}}">{{school}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group mb-2">
                    <label for="department">Department</label>
                    <select class="form-control" name="department" id="department">
                        {% for department in departments %}
                        <option value="{{department}}">{{department}}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save Author</button>
                  </div>
            </form>
        </div>
        
      </div>
    </div>
  </div>

<!-- Authors from CSV-->
<div class="modal fade" id="bulkAuthor" tabindex="-1" aria-labelledby="bulkAuthorLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable"" >
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="bulkAuthorLabel">Upload Authors CSV File</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="{% url 'dashboard:bulk_upload_authors' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group mb-2">
                    <label for="name">Authors File</label>
                    <input type="file" accept=".csv" name="csv_file" class="form-control">
                </div>
                <div class="form-group mb-2">
                    <label for="name">Sample File Format</label>
                    <small class="text-info"><a href="{% url 'dashboard:download_aut_csv' %}" class="text-primary" target="_blank">Download Sample File Format</a></small>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Upload Authors</button>
                </div>
            </form>
        </div>
        
      </div>
    </div>
  </div>

{% endblock %}
{% block custom_scripts %}
<script>
	  
    $(document).ready(function() {
    $('#example').DataTable()
  });
    
  </script>
  
  
  <script>
      $(document).ready(function() {
          var table = $('#example2').DataTable( {
              lengthChange: false,
              buttons: [ 'copy', 'excel', 'pdf', 'print']
          } );
       
          table.buttons().container()
              .appendTo( '#example2_wrapper .col-md-6:eq(0)' );
      } );
  </script>
{% endblock custom_scripts %}

ug_scholar/dashboard/templates/pages/departments.html
{% extends "base/base.html" %}
{% load static %}
{% load humanize %}
{% block content %}
<div class="page-wrapper">
    <div class="page-content">
        <!--breadcrumb-->
        <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
            <div class="breadcrumb-title pe-3">Departments</div>
            <div class="ps-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-0 p-0">
                        <li class="breadcrumb-item"><a href="javascript:;"><i class="bx bx-home-alt"></i></a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">Departments</li>
                    </ol>
                </nav>
            </div>
           
        </div>
        <!--end breadcrumb-->
        <h6 class="mb-0 text-uppercase">Departments Information</h6>
        <hr/>
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example" class="table table-striped table-bordered" style="width:100%">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>AUTHORS</th>
                                <th>PUBLICATIONS</th>
                                <th>CITATIONS</th>
                                <th>H-INDEX</th>
                                <th>I10-INDEX</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if department_breakdown_info %}
                            {% for info in department_breakdown_info %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td><a href="{% url 'dashboard:department_details' %}?department={{info.department}}">{{info.department}}</a></td>
                                <td>{{info.total_authors|intcomma }}</td>
                                <td>{{info.total_publications|intcomma }}</td>
                                <td>{{info.total_citations|intcomma }}</td>
                                <td>{{info.total_h_index|intcomma }}</td>
                                <td>{{info.total_i10_index|intcomma }}</td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <tr>
                                <td colspan="6" class="text-center">No Info Available</td>
                            </tr>
                            {% endif %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>AUTHORS</th>
                                <th>PUBLICATIONS</th>
                                <th>CITATIONS</th>
                                <th>H-INDEX</th>
                                <th>I10-INDEX</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_scripts %}
<script>
	  
    $(document).ready(function() {
    $('#example').DataTable()
  });
    
  </script>
  
  
  <script>
      $(document).ready(function() {
          var table = $('#example2').DataTable( {
              lengthChange: false,
              buttons: [ 'copy', 'excel', 'pdf', 'print']
          } );
       
          table.buttons().container()
              .appendTo( '#example2_wrapper .col-md-6:eq(0)' );
      } );
  </script>
{% endblock custom_scripts %}