ug_scholar/accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

ug_scholar/api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('', views.OverviewAPI.as_view(), name='overview'),
    path('populate-db/', views.PopulateDBAPIView.as_view(), name='populate-db'),
]

ug_scholar/dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"

# dashboard
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

# administrators
urlpatterns += [
    path('administrators/', views.AdministratorsView.as_view(), name='administrators'),
    path('create-administrator/', views.CreateUpdateAdministratorView.as_view(), name='create_administrator'), #noqa
]

# author and publications
urlpatterns += [
    path('authors/', views.AuthorsView.as_view(), name='authors'),
    path('create-author/', views.CreateUpdateAuthorView.as_view(), name='create_author'),
    path('publications/', views.PublicationsView.as_view(), name='publications'),
    path('download-sample-file/', views.DownloadSampleBulkFileView.as_view(), name='download_aut_csv'), #noqa
    path('bulk-upload-authors/', views.BulkUploadAuthorView.as_view(), name='bulk_upload_authors'), #noqa
]

# breakdown
urlpatterns += [
    path('colleges/', views.CollegesView.as_view(), name='colleges'),
    path('college-details/', views.CollegeDetailsView.as_view(), name='college_details'),
    path('institutions-and-centers/', views.FacultiesView.as_view(), name='faculties'),
    path('institution-details/', views.FacultyDetailsView.as_view(), name='institution_details'),
    path('departments/', views.DepartmentsView.as_view(), name='departments'),
    path('department-details/', views.DepartmentDetailsView.as_view(), name='department_details'), #noqa
]

# profile
urlpatterns += [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('change-profile-picture/', views.ChangeProfilePictureView.as_view(), name='change_pp'), #noqa
]

# logs
urlpatterns += [
    path('logs/', views.LogsView.as_view(), name='logs'),
]

ug_scholar/ug_scholar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    path('', include('accounts.urls')),
    path('api/', include('api.urls')),
]


# Let django serve static files in development mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

ug_scholar/dashboard/models.py
from django.db import models

# Create your models here.

ug_scholar/dashboard/forms.py
from django import forms

from api.models import Profile


class AuthorProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['thumbnail', 'statistics', ]

ug_scholar/dashboard/views/administrators.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.views import View

from accounts.models import User
from ug_scholar.library.decorators import AdministratorsOnly
from ug_scholar.library.utils_functions import log_user_action


class AdministratorsView(View):
    '''Renders the administrators page'''
    template_name = 'pages/administrators.html'
    
    @method_decorator(AdministratorsOnly)
    def get(self, request):
        user = request.user
        administrators = User.objects.all()
        log_user_action(user, "Viewed administrators page")
        context = {
            'administrators': administrators
        }
        return render(request, self.template_name, context)
    
  
class CreateUpdateAdministratorView(View):
    '''Renders the create/update administrators page'''
    
    @method_decorator(AdministratorsOnly)
    def get(self, request):
        user = request.user
        log_user_action(user, "Tried to access admin creation form via get request")
        return redirect('dashboard:administrators')    
    
    @method_decorator(AdministratorsOnly)
    def post(self, request):
        user = request.user
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')
        fullname = request.POST.get('fullname')
        
        admin = User.objects.filter(email=email).first()
        if password != password2:
            log_user_action(user, "Tried to create admin account with mismatching passwords")
            messages.info(request, "Passwords Do Not Match")
            return redirect('dashboard:administrators')
        
        if admin is not None:
            log_user_action(user, "Tried to create admin account with an already existing email")
            messages.info(request, "Email is Already Associated with an Account")
            return redirect('dashboard:administrators')
        try:
            new_admin = User.objects.create_user(email=email, password=password, fullname=fullname)
            new_admin.is_staff = True
            new_admin.save()
        except Exception as e:
            log_user_action(user, f"Tried to create admin account but error occured: {str(e)}")
            messages.info(request, "Error Creating Administrator Account")
            return redirect('dashboard:administrators')
        else:
            log_user_action(user, f"Created admin account: {new_admin.fullname} successfully")
            messages.success(request, "Administrator Account Created Successfully")
        return redirect('dashboard:administrators')

ug_scholar/dashboard/views/authors.py
import csv
import os
import json
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.utils.html import strip_tags
from django.views import View

from api.models import Author, Profile, Publication
from dashboard.forms import AuthorProfileForm
from dashboard.views import publications
from dashboard.views.publications import PublicationsView
from ug_scholar.library.constants import UG, SampleAuthorData
from ug_scholar.library.decorators import AdministratorsOnly
from ug_scholar.library.utils_functions import get_author_ids, log_user_action, scrape_author_data


class AuthorsView(View):
    '''Renders the authors profiles page - profiles page'''
    template_name = 'pages/authors.html'

    def get(self, request):
        ug = UG()
        authors = Profile.objects.all()

        schools = ug.get_schools()
        departments = ug.get_departments()
        colleges = ug.get_colleges()
        ranks = ug.get_ranks()

        context = {
            'authors': authors,
            'colleges': colleges,
            'schools': schools,
            'departments': departments,
            'ranks': ranks,
        }
        return render(request, self.template_name, context)


class CreateUpdateAuthorView(View):
    '''Renders the create/update author page'''

    def get(self, request):
        user = request.user
        log_user_action(user, "Tried to access author form using get request")
        return redirect('dashboard:authors')

    @method_decorator(AdministratorsOnly)
    def post(self, request):
        user = request.user
        scholar_id = request.POST.get('scholar_id')
        profile = Profile.objects.filter(scholar_id=scholar_id).first()
        if profile is not None:
            log_user_action(user, "Tried to create author profile with an already existing scholar id") #noqa
            messages.info(request, "Author Profile Already Exists")
            return redirect('dashboard:authors')
        # author does not exist, create new author profile
        print(f"Scrapping author data for profile: {scholar_id}")
        try:
            scraped = scrape_author_data(scholar_id)
        except Exception as e:
            messages.info(request, f"Error occured: {e}")
            return redirect('dashboard:authors')
        author_data = scraped["author_data"]
        form = AuthorProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            if author_data is not None or author_data != {}:
                profile.name = author_data['name']
                profile.affiliation = author_data['affiliations']
                profile.thumbnail = author_data['thumbnail']
                profile.interests = json.dumps(author_data['interests'])
                profile.statistics = json.dumps(author_data['cited_by_table'])
            profile.save()
            author = Author.objects.create(profile=profile)
            author.save()
            log_user_action(user, f"Created author profile: {profile.name} successfully") #noqa
            messages.success(request, "Author Profile Created Successfully")
            return redirect('dashboard:authors')
        else:
            for field, error in form.errors.items():
                message = f"{field.title()}: {strip_tags(error)}"
                log_user_action(user, f"Tried to create author profile but error occured: {message}") #noqa
                messages.info(request, message)
                return HttpResponseRedirect(request.META.get("HTTP_REFERER"))


class BulkUploadAuthorView(View):
    '''Used to implement bulk upload of author profiles: POST request'''

    def get(self, request):
        user = request.user
        log_user_action(user, "Tried to access bulk upload author form using get request")  # noqa
        return redirect('dashboard:authors')

    def post(self, request):
        updated_authors = 0
        updated_publications = 0
        csv_file = request.FILES.get('csv_file')
        try:
            infos = get_author_ids(csv_file)
        except Exception as e:
            messages.info(request, f"Error occured: {e}")
            return redirect('dashboard:authors')

        for info in infos:
            old_profile = Profile.objects.filter(scholar_id=info['author_id']).first()  # noqa
            if old_profile is not None:
                print(f"Skipping Profile: {old_profile.name}")
                print("+==================================================+")
                print("+==================================================+")
                continue
            scraped = scrape_author_data(info['author_id'])
            author_data = scraped["author_data"]
            # check if profile exists  - if not create profile
            profile = Profile.objects.filter(scholar_id=info['author_id']).first()  # noqa
            if profile is None:
                profile = Profile.objects.create(
                    name=author_data['name'],
                    scholar_id=info['author_id'],
                    affiliation=author_data['affiliations'],
                    thumbnail=author_data['thumbnail'],
                    interests=json.dumps(author_data['interests']),
                    statistics=json.dumps(author_data['cited_by_table']),
                    rank=info['rank'],
                    email=info['email'],
                    college=info['college'],
                    school=info['school'],
                    department=info['department'],
                )
                profile.save()
                print(f"Created profile: {profile.name}")
            
            # check if author exists. if not create author
            author = Author.objects.filter(profile=profile).first()
            if author is None:
                author = Author.objects.create(profile=profile)
                author.save()
            # get all authors articles/publications
            author_articles = scraped["author_articles"]

            print(f"Updating author: {author.profile.name}")
            # create publications
            for article in author_articles:
                publication = Publication.objects.filter(citation_id=article['article_citation_id']).first()  # noqa
                # Handle null citation values
                citation_value = article['article_cited_by_value']
                article_year = article['article_year']
                if citation_value is None or citation_value == "":
                    citation_value = 0
                else:
                    # make sure citation value is an integer
                    citation_value = int(citation_value)
                if article_year is None or article_year == "":
                    article_year = 1900
                else:
                    # make sure article year is a number
                    article_year = int(article_year)

                if publication is None:
                    # create new publication
                    publication = Publication.objects.create(
                        title=article['article_title'],
                        year=article_year,
                        link=article['article_link'],
                        citation_id=article['article_citation_id'],
                        authors=article['article_authors'],
                        journal=article['article_publication'],
                        citations=citation_value,
                    )
                    publication.save()
                else:
                    # update publication
                    publication.title = article['article_title']
                    publication.year = article_year
                    publication.link = article['article_link'],
                    publication.citation_id = article['article_citation_id']
                    publication.authors = article['article_authors']
                    publication.journal = article['article_publication']
                    publication.citations = citation_value
                    publication.save()
                # add publication to author if not already added
                if publication not in author.publications.all():
                    author.publications.add(publication)
                    author.save()
                else:
                    # remove the old publication and add the new one
                    author.publications.remove(publication)
                    author.publications.add(publication)
                    author.save()
                # update the count of updated publications and authors
                updated_publications += 1
            updated_authors += 1
        messages.success(request, f"Updated {updated_authors} authors with {updated_publications} publications")  # noqa
        log_user_action(request.user, "Updated the system using bulk author upload successfully")  # noqa
        return redirect('dashboard:authors')


class DownloadSampleBulkFileView(View):
    '''Used to download a sample csv file for bulk upload'''

    def get(self, request):
        sample_data = SampleAuthorData().get_author_sample_data()
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="bulk_author_upload_sample.csv"'

        writer = csv.writer(response)
        writer.writerow(['scholar', 'email', "college", 'school', 'department', 'rank']) # noqa
        
        for data in sample_data:
            writer.writerow([data['scholar'], data['email'], data['college'], data['school'], data['department'], data['rank']])
            
        return response

ug_scholar/dashboard/views/logs.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View

from accounts.models import UserLog
from ug_scholar.library.decorators import AdministratorsOnly
from ug_scholar.library.utils_functions import log_user_action


class LogsView(View):
    '''Renders the logs page'''
    template_name = 'pages/logs.html'
    
    @method_decorator(AdministratorsOnly)
    def get(self, request):
        user = request.user
        logs = UserLog.objects.all().order_by("-created_at")
        context = {
           "logs": logs
        }
        log_user_action(user, "Accessed the logs page")
        return render(request, self.template_name, context)
    
    

ug_scholar/dashboard/views/publications.py
from django.shortcuts import render
from django.views import View

from api.models import Publication


class PublicationsView(View):
    template_name = 'pages/publications.html'
    
    def get(self, request):
        publications = Publication.objects.all()
        
        context = {
            'publications': publications,
        }
        return render(request, self.template_name, context)

ug_scholar/dashboard/templates/includes/header.html
{% load static %}
<header>
    <div class="topbar d-flex align-items-center">
        <nav class="navbar navbar-expand gap-3">
            <div class="mobile-toggle-menu"><i class='bx bx-menu'></i>
            </div>
            <div class="search-bar flex-grow-1">
                <div class="position-relative search-bar-box">
                    <input type="text" class="form-control search-control" placeholder="Type to search..."> <span class="position-absolute top-50 search-show translate-middle-y"><i class='bx bx-search'></i></span>
                    <span class="position-absolute top-50 search-close translate-middle-y"><i class='bx bx-x'></i></span>
                </div>
            </div>
            <div class="top-menu ms-auto">
                <ul class="navbar-nav align-items-center gap-1">
                    <li class="nav-item mobile-search-icon d-flex d-lg-none" data-bs-toggle="modal" data-bs-target="#SearchModal">
                        <a class="nav-link" href="avascript:;"><i class='bx bx-search'></i>
                        </a>
                    </li>

                    <li class="nav-item dropdown dropdown-app">
                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-bs-toggle="dropdown" href="javascript:;"><i class='bx bx-grid-alt'></i></a>
                        <div class="dropdown-menu dropdown-menu-end p-0">
                            <div class="app-container p-2 my-2">
                                <div class="row gx-0 gy-2 row-cols-3 justify-content-center p-2">
                                    <div class="col">
                                        <a href="https://scholar.google.com/" target="_blank">
                                            <div class="app-box text-center">
                                                <div class="app-icon">
                                                    <img src="{% static 'dashboard/assets/images/app/google-scholar.png' %}" width="30" alt="">
                                                </div>
                                                <div class="app-name">
                                                    <p class="mb-0 mt-1">Google Scholar</p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div class="col">
                                        <a href="https://www.scopus.com/" target="_blank">
                                            <div class="app-box text-center">
                                                <div class="app-icon">
                                                    <img src="{% static 'dashboard/assets/images/app/scopus.jpeg' %}" width="30" alt="">
                                                </div>
                                                <div class="app-name">
                                                    <p class="mb-0 mt-1">Scopus</p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div class="col">
                                        <a href="https://www.webofscience.com/wos/woscc/basic-search" target="_blank">
                                            <div class="app-box text-center">
                                                <div class="app-icon">
                                                    <img src="{% static 'dashboard/assets/images/app/web-of-science.jpeg' %}" width="30" alt="">
                                                </div>
                                                <div class="app-name">
                                                    <p class="mb-0 mt-1">Web of Science</p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                    <div class="col">
                                        <a href="https://www.linkedin.com/" target="_blank">
                                            <div class="app-box text-center">
                                                <div class="app-icon">
                                                    <img src="{% static 'dashboard/assets/images/app/linkedin.png' %}" width="30" alt="">
                                                </div>
                                                <div class="app-name">
                                                    <p class="mb-0 mt-1">linkedin</p>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <!--end row-->

                            </div>
                        </div>
                    </li>

                    <li class="nav-item dropdown dropdown-large">
                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret position-relative" href="#" data-bs-toggle="dropdown"><span class="alert-count">0</span>
                            <i class='bx bx-bell'></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <a href="javascript:;">
                                <div class="msg-header">
                                    <p class="msg-header-title">Notifications</p>
                                    <p class="msg-header-badge">0 New</p>
                                </div>
                            </a>
                            <div class="header-notifications-list">
                                <!-- put notifications here later -->
                            </div>
                            <a href="javascript:;">
                                <div class="text-center msg-footer">
                                    <button class="btn btn-light w-100">View All Notifications</button>
                                </div>
                            </a>
                        </div>
                    </li>
                    
                </ul>
            </div>

            <div class="user-box dropdown px-3">
                <a class="d-flex align-items-center nav-link dropdown-toggle gap-3 dropdown-toggle-nocaret" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    
                    {% if request.user.is_authenticated and request.user.is_superuser or request.user.is_staff %}
                    <img src="{% if request.user.profile_picture %} {{request.user.profile_picture.url}} {% else %} {% static 'dashboard/assets/images/app/google-scholar.png' %} {% endif %}" class="user-img" alt="user avatar">
                    {% else %}
                    <img src="{% static 'dashboard/assets/images/app/google-scholar.png' %}" class="user-img" alt="user profile">
                    {% endif %}
                    
                    <!-- Do conditional rendering here - only admins -->
                    {% if request.user.is_authenticated and request.user.is_superuser or request.user.is_staff %}
                    <div class="user-info">
                        <p class="user-name mb-0">{{ request.user.fullname }}</p>
                        {% if request.user.is_superuser %}
                        <p class="designation mb-0">Superuser</p>
                        {% elif request.user.is_staff %}
                        <p class="designation mb-0">Staff</p>
                        {% endif %}
                    </div>
                    {% endif %}
                </a>
                <!-- Do conditional rendering here - only admins -->
                <ul class="dropdown-menu dropdown-menu-end">
                    {% if request.user.is_authenticated and request.user.is_superuser or request.user.is_staff %}
                    <li><a class="dropdown-item d-flex align-items-center" href="{% url 'dashboard:profile' %}"><i class="bx bx-user fs-5"></i><span>Profile</span></a></li>
                    {% endif %}
                    {% if request.user.is_authenticated and request.user.is_superuser or request.user.is_staff %}
                    <li><a class="dropdown-item d-flex align-items-center" href="{% url 'accounts:logout' %}"><i class="bx bx-log-out-circle"></i><span>Logout</span></a></li>
                    {% else %}
                    <button type="button" class="btn btn-light" style="width: 100%;" data-bs-toggle="modal" data-bs-target="#loginModal">Login</button>
                    {% endif %}
                </ul>
            </div>
            

        </nav>
    </div>
</header>

<!-- Login form modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable"" >
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="loginModalLabel">Login</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="{% url 'accounts:login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group mb-2">
                    <label for="email">Email</label>
                    <input type="email" name="email" placeholder="eg. princek@gmail.com" class="form-control">
                </div>
                <div class="form-group mb-2">
                    <label for="password">Password</label>
                    <input type="password" name="password" placeholder="Enter password" class="form-control">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Login As Staff</button>
                  </div>
            </form>
        </div>
        
      </div>
    </div>
  </div>

ug_scholar/dashboard/templates/includes/sidebar.html
{% load static %}
<div class="sidebar-wrapper" data-simplebar="true">
    <div class="sidebar-header">
        <div>
            <img src="{% static 'dashboard/assets/images/logo.png' %}" style="height: 40px; width:auto;" class="logo-icon" alt="logo icon">
        </div>
        <div>
            <h4 class="logo-text">IntelliSphere</h4>
        </div>
        <div class="toggle-icon ms-auto"><i class='bx bx-arrow-back'></i>
        </div>
    </div>
    <!--navigation-->
    <ul class="metismenu" id="menu">
        <li>
            <a href="{% url 'dashboard:index' %}">
                <div class="parent-icon"><i class='bx bx-home'></i>
                </div>
                <div class="menu-title">Dashboard</div>
            </a>
        </li>
        <li>
            <a href="{% url 'dashboard:authors' %}">
                <div class="parent-icon"><i class='bx bx-group'></i>
                </div>
                <div class="menu-title">Authors</div>
            </a>
        </li>
        <li>
            <a href="{% url 'dashboard:publications' %}">
                <div class="parent-icon"><i class='bx bx-book-content'></i>
                </div>
                <div class="menu-title">Publications</div>
            </a>
        </li>
        <li class="menu-label">Break Down</li>
        <li>
            <a href="javascript:;" class="has-arrow">
                <div class="parent-icon"><i class='bx bx-time'></i>
                </div>
                <div class="menu-title">Break Down</div>
            </a>
            <ul>
                <li> <a href="{% url 'dashboard:colleges' %}"><i class='bx bx-radio-circle'></i>Colleges</a>
                </li>
                <li> <a href="{% url 'dashboard:faculties' %}"><i class='bx bx-radio-circle'></i>Institutes & Centers</a>
                </li>
                <li> <a href="{% url 'dashboard:departments' %}"><i class='bx bx-radio-circle'></i>Departments</a>
                </li>
            </ul>
        </li>

        <!-- conditional rendering - only for administrators-->
        {% if request.user.is_superuser or request.user.is_staff %}
        <li class="menu-label">Accounts</li>
        <li>
            <a href="{% url 'dashboard:administrators' %}">
                <div class="parent-icon"><i class="bx bx-user"></i>
                </div>
                <div class="menu-title">Administrators</div>
            </a>
        </li>
        <li>
            <a href="{% url 'dashboard:logs' %}">
                <div class="parent-icon"><i class="bx bx-edit"></i>
                </div>
                <div class="menu-title">Logs</div>
            </a>
        </li>
        {% endif %}


    </ul>
    <!--end navigation-->
</div>